//! finupdate's GTK-free backend.
//!
//! Everything here compiles and tests without a GTK toolchain — no `gtk4`, no
//! `libadwaita`, no display. That is the whole reason the crate exists:
//! `cargo test -p finupdate-core` runs on a machine that cannot build GTK4,
//! which is where much of this project's development happens.
//!
//! The split follows the same shape as `tuna-os/gtk-office-suite`'s
//! `letters-core` / `letters` pair. The abstraction was already present here —
//! [`service::UpdaterService`] with a fixture-backed implementation, plus a
//! headless `finupdate-cli` that links the service without the UI — but nothing
//! *enforced* it. A separate crate does: a `use gtk::…` in this crate is now a
//! compile error rather than a code-review note.
//!
//! # What lives here
//!
//! | Module | Role |
//! |---|---|
//! | [`service`] | The `UpdaterService` trait and its bootc-backed impl |
//! | [`registry_client`] | GHCR queries, image-ref parsing, family resolution |
//! | [`bootc_probe`] | Host bootc/os-release introspection and its pure parsers |
//! | [`sbom_diff`] | SPDX fetch and package diffing |
//! | [`orchestrator`] | Runs `finupdate-runner` and parses its marker protocol |
//! | [`update_worker`] | Update event stream, including the simulator |
//! | [`uupd_compat`] | Optional host `uupd` integration |
//! | [`settings`] | Preferences, GSettings-backed with a JSON fallback |
//! | [`privileged`] | The single chokepoint for privileged host commands |
//! | [`action_journal`] | JSONL record of every intended privileged action |
//! | [`runtime`] | The one shared tokio runtime |
//! | [`gpu`] | GPU detection for the NVIDIA variant hint |
//! | [`config`] | Build-time constants, generated by meson |
//!
//! # What deliberately does not
//!
//! `dbus_progress` stays in the GUI crate: it publishes app state for the GNOME
//! Shell extension and is meaningful only to a running frontend.

pub mod action_journal;
pub mod bootc_probe;
pub mod config;
pub mod gpu;
pub mod orchestrator;
pub mod privileged;
pub mod registry_client;
pub mod runtime;
pub mod sbom_diff;
pub mod service;
pub mod settings;
#[cfg(test)]
pub mod test_support;
pub mod update_worker;
pub mod uupd_compat;
pub mod version_compare;
pub mod version_parse;
